export const CommitteesData = [
  {
    id: 1,
    number: 2211,
    services: 11,
    name: 'لجنة الشؤون القانونية',
    status: 1,
    department: 'إدارة الخدمات التخصصية',
    upcomingMeetings: 12,
    previousMeetings: 3,
    pendingActions: 8,
    projects: 15,
    startDate: '2024-08-14',
    InitiatieDate: '2024-08-01',
    members: 13,
    tasks: [
      { count: 40, label: 'منجزة', color: 'Green' },
      { count: 2, label: 'قيد الإجراء', color: 'Orange' },
      { count: 4, label: 'متأخرة', color: 'Red' },
    ],
    peopleDetails: [
      { id: 1, name: 'Ahmed Ali', role: 'رئيس اللجنة' },
      { id: 2, name: 'Fatima Hassan', role: 'نائب الرئيس' },
      { id: 3, name: 'Mohammed Saleh', role: 'عضو' },
      { id: 4, name: 'Sara Ahmad', role: 'عضو' },
      { id: 5, name: 'Khaled Youssef', role: 'مستشار قانوني' },
      { id: 6, name: 'Amal Nasser', role: 'منسق' },
      { id: 7, name: 'Rania Omar', role: 'عضو' },
      { id: 8, name: 'Yousef Al-Qassim', role: 'عضو' },
      { id: 9, name: 'Hiba Mustafa', role: 'منسق' },
      { id: 10, name: 'Omar Hussein', role: 'عضو' },
      { id: 11, name: 'Nour Al-Din', role: 'عضو' },
      { id: 12, name: 'Ayman Ziad', role: 'مستشار' },
      { id: 13, name: 'Lina Mahmoud', role: 'مستشار' },
    ],
    meetingsDetails: [
      {
        id: 1,
        name: 'اجتماع تشاوري',
        time: '2024-09-01T10:00:00',
        invited: ['Ahmed Ali', 'Fatima Hassan', 'Mohammed Saleh'],
        agenda: 'مناقشة السياسات القانونية الجديدة وتحديد الخطوات التالية.',
        location: 'قاعة الاجتماعات 1',
        notes: 'يجب التركيز على البند الأول من جدول الأعمال.',
      },
      {
        id: 2,
        name: 'اجتماع تخطيطي',
        time: '2024-09-10T14:00:00',
        invited: ['Sara Ahmad', 'Khaled Youssef', 'Amal Nasser'],
        agenda: 'وضع الخطط التنفيذية للأشهر القادمة.',
        location: 'قاعة الاجتماعات 2',
        notes: 'يجب تقديم التقارير الأولية قبل الاجتماع.',
      },
      {
        id: 3,
        name: 'اجتماع تنسيقي',
        time: '2024-09-15T11:00:00',
        invited: ['Ahmed Ali', 'Rania Omar', 'Yousef Al-Qassim'],
        agenda: 'تنسيق المهام بين أعضاء اللجنة.',
        location: 'قاعة الاجتماعات 3',
        notes: 'يجب أن يكون كل الأعضاء جاهزين بالتحديثات.',
      },
      {
        id: 4,
        name: 'اجتماع متابعة',
        time: '2024-09-20T09:00:00',
        invited: ['Hiba Mustafa', 'Omar Hussein', 'Nour Al-Din'],
        agenda: 'متابعة تنفيذ المهام ومراجعة التقدم.',
        location: 'قاعة الاجتماعات 1',
        notes: 'يرجى الحضور في الوقت المحدد.',
      },
      {
        id: 5,
        name: 'اجتماع تقرير نصف سنوي',
        time: '2024-09-25T16:00:00',
        invited: ['Ayman Ziad', 'Lina Mahmoud', 'Khaled Youssef'],
        agenda: 'عرض ومناقشة التقرير نصف السنوي.',
        location: 'قاعة الاجتماعات 2',
        notes: 'يرجى إرسال التقارير النهائية قبل الاجتماع.',
      },
      {
        id: 6,
        name: 'اجتماع تقييم الأداء',
        time: '2024-09-28T13:00:00',
        invited: ['Ahmed Ali', 'Fatima Hassan', 'Amal Nasser'],
        agenda: 'تقييم أداء اللجنة والأنشطة المنجزة.',
        location: 'قاعة الاجتماعات 3',
        notes: 'يجب تقديم المقترحات لتحسين الأداء.',
      },
    ],
    files: [
      { id: 1, name: 'محضر اجتماع تشاوري.pdf' },
      { id: 2, name: 'خطة العمل.pdf' },
      { id: 3, name: 'تقرير الأداء نصف سنوي.pdf' },
      { id: 4, name: 'مسودة السياسات القانونية.docx' },
    ],
  },
  {
    id: 2,
    number: 2212,
    services: 12,
    name: 'لجنة الشؤون الإستراتيجية',
    previousMeetings: 3,
    status: 2,
    department: 'إدارة الخدمات التخصصية',
    upcomingMeetings: 8,
    pendingActions: 8,
    InitiatieDate: '2024-08-01',
    projects: 4,
    startDate: '2024-08-14',
    members: 18,
    tasks: [
      { count: 33, label: 'منجزة', color: 'Green' },
      { count: 10, label: 'قيد الإجراء', color: 'Orange' },
      { count: 8, label: 'متأخرة', color: 'Red' },
    ],
    people: [
      { id: 3, name: 'Mohammed Saleh' },
      { id: 4, name: 'Sara Ahmad' },
    ],
    meetingsDetails: [
      {
        id: 3,
        name: 'اجتماع استراتيجي',
        time: '2024-09-05T11:00:00',
        invited: ['Mohammed Saleh', 'Sara Ahmad'],
      },
      {
        id: 4,
        name: 'اجتماع تنفيذي',
        time: '2024-09-12T13:00:00',
        invited: ['Khaled Youssef', 'Amal Nasser'],
      },
    ],
  },
  {
    id: 3,
    number: 8849,
    previousMeetings: 3,
    services: 4,
    name: 'لجنة متابعة مبادرات تحقيق الرؤية',
    status: 1,
    department: 'إدارة الخدمات التخصصية',
    upcomingMeetings: 4,
    pendingActions: 1,
    projects: 23,
    members: 5,
    InitiatieDate: '2024-08-01',
    startDate: '2024-08-14',
    tasks: [
      { count: 50, label: 'منجزة', color: 'Green' },
      { count: 34, label: 'قيد الإجراء', color: 'Orange' },
      { count: 5, label: 'متأخرة', color: 'Red' },
    ],
    people: [
      { id: 5, name: 'Amal Nasser' },
      { id: 6, name: 'Rania Omar' },
    ],
    meetingsDetails: [
      {
        id: 5,
        name: 'اجتماع متابعة',
        time: '2024-09-07T09:00:00',
        invited: ['Amal Nasser', 'Rania Omar'],
      },
      {
        id: 6,
        name: 'اجتماع تقني',
        time: '2024-09-15T15:00:00',
        invited: ['Yousef Al-Qassim', 'Hiba Mustafa'],
      },
    ],
  },
  {
    id: 4,
    previousMeetings: 3,
    number: 3406,
    services: 7,
    name: 'لجنة شوؤن الموظفين',
    status: 1,
    department: 'إدارة الخدمات التخصصية',
    InitiatieDate: '2024-08-01',
    upcomingMeetings: 3,
    pendingActions: 18,
    members: 14,
    projects: 6,
    startDate: '2024-08-14',
    tasks: [
      { count: 12, label: 'منجزة', color: 'Green' },
      { count: 8, label: 'قيد الإجراء', color: 'Orange' },
      { count: 0, label: 'متأخرة', color: 'Red' },
    ],
    people: [
      { id: 7, name: 'Omar Hussein' },
      { id: 8, name: 'Nour Al-Din' },
    ],
    meetingsDetails: [
      {
        id: 7,
        name: 'اجتماع الموظفين',
        time: '2024-09-02T11:30:00',
        invited: ['Omar Hussein', 'Nour Al-Din'],
      },
    ],
  },
  {
    id: 5,
    number: 8655,
    services: 3,
    name: 'لجنة الشؤون المالية',
    previousMeetings: 3,
    status: 2,
    department: 'إدارة الخدمات التخصصية',
    upcomingMeetings: 0,
    pendingActions: 1,
    InitiatieDate: '2024-08-01',
    projects: 1,
    members: 36,
    startDate: '2024-08-14',
    tasks: [
      { count: 3, label: 'منجزة', color: 'Green' },
      { count: 1, label: 'قيد الإجراء', color: 'Orange' },
      { count: 1, label: 'متأخرة', color: 'Red' },
    ],
    people: [
      { id: 9, name: 'Ayman Ziad' },
      { id: 10, name: 'Lina Mahmoud' },
    ],
    meetingsDetails: [],
  },
  {
    id: 6,
    number: 7869,
    previousMeetings: 3,
    services: 14,
    name: 'لجنة المشتريات والعقود',
    status: 1,
    department: 'إدارة الخدمات التخصصية',
    upcomingMeetings: 12,
    pendingActions: 3,
    projects: 6,
    members: 7,
    InitiatieDate: '2024-08-01',
    startDate: '2024-08-14',
    tasks: [
      { count: 11, label: 'منجزة', color: 'Green' },
      { count: 3, label: 'قيد الإجراء', color: 'Orange' },
      { count: 1, label: 'متأخرة', color: 'Red' },
    ],
    people: [
      { id: 11, name: 'Rami Ibrahim' },
      { id: 12, name: 'Fadi Hassan' },
    ],
    meetingsDetails: [
      {
        id: 8,
        name: 'اجتماع المشتريات',
        time: '2024-09-09T10:30:00',
        invited: ['Rami Ibrahim', 'Fadi Hassan'],
      },
    ],
  },
];
